version: '3.9'

services:
  acquiring-bank:
    build:
      context: .
      dockerfile: AcquiringBankSimulator/src/AcquiringBankSimulator.Api/Dockerfile
    image: acquiring-bank
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5370:5370
    networks:
      - payment-gateway
  
  payment-api:
    build:
      context: .
      dockerfile: PaymentGateway/src/PaymentGateway.Api/Dockerfile
    image: payment-api
    depends_on:
      - acquiring-bank
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ACQUIRING_BANK_ENDPOINT: http://acquiring-bank:5370
    ports:
      - 5270:5270
    networks:
      - payment-gateway

networks:
  payment-gateway:
    driver: bridge